### PR TITLE
c89-fixes and lua-binding for kazmath

### PR DESCRIPTION
**Pull request by rocaltair**
* add all functions for kazmath/*.h (except kazmath/GL/*.h)
* lkazmath.km* for all functions
* use lkazmath.*New or lkazmath.*NewWithArray or lkazmath.*NewWithTbl to create a object (struct in C)
* method ToArray, ToTbl for vec*, mat*
* OOP support (without prefix km${StructName}), for example 
```
mat3 = lkazmath.kmMat3New()
mat3:ToArray()
```
or you can use
```
lkazmath.kmMat3ToArray(mat3)
```
* alter args(such as kmScalar *out are removed from function params), see lua__kmMat4RotationToAxisAngle, lua__kmLine2WithLineIntersection

see [More...](https://github.com/rocaltair/kazmath/blob/master/lua/README.md)

### CODE REVIEW

**Comment by Kazade** [comment]
Sorry this PR completely slipped past me! I'll bring it up to date and merge it when I can. Thanks I really appreciate your work!

**Comment by rocaltair** [comment]
Shall I send another pull request to resolve these conflicts?

**Comment by rocaltair** [comment]
hi~ @Kazade , I fixed these conflicts. But I found some error while turning on KAZMATH_BUILD_TESTS flag on Mac OS X.

**Comment by Kazade** [comment]
Thanks for this! Just trying to find a window of time to review, test and merge!

**Comment by rocaltair** [comment]
:-)

**Comment by Kazade** [comment]
Finally merged! Thanks!!

**Pull request merged**
