### PR TITLE
AABB 2d and quad

### PR DESCRIPTION
**Pull request by dhontecillas**
C code:
- Renamed AABB to AABB3 
- Added AABB2 
- Put common code for intersections in ray2.c into a separate function kmLine2WithLineIntersection, that finds the intersection point, but also returns the "factor" values, so it can be checked if we are looking for a two segment intersection, an infinite ray to segment or whatever
C++ code: 
- Added the AABB2 class 
- Added a quad class (non axis aligned box)
- Added the unary minus operator to vec*.h 
- Added the BoundVec2 class : ( this is subject to be changed : for now the main reason to use this name instead of "ray" is for comparisons, and when moving to 3d, this class can define a ray, a line, or a plane , depending on its interpretation )

### CODE REVIEW

**Comment by Kazade** [comment]
Hey!

I've finally had a chance to look at this. I've added an extra commit (083431c714094b02bf4cedce34512374a873bac7) to bring the CMakeLists.txt files and Java bindings up to date (kmAABB2 isn't in the Java bindings yet though). 

I have found one problem though, and I was hoping you could shed some light on it. In this branch the kmRay2 tests have started failing, here's the output I get:

```
/home/lukeb/Git/kazmath/tests/test_ray3.cpp:20:1: error: Failure in test_ray_plane_intersection: Expected 0 +/- 0.0001 but was -1
/home/lukeb/Git/kazmath/tests/test_ray3.cpp:21:1: error: Failure in test_ray_plane_intersection: Expected 10 +/- 0.0001 but was 0
/home/lukeb/Git/kazmath/tests/test_ray2.cpp:15:1: error: Failure in test_line_segment_intersection: kmRay2IntersectLineSegment(&ray, &line_start, &line_end, &intersect)
/home/lukeb/Git/kazmath/tests/test_ray2.cpp:18:1: error: Failure in test_line_segment_intersection: Expected 1 +/- 0.001 but was 4.59163e-41
/home/lukeb/Git/kazmath/tests/test_ray2.cpp:32:1: error: Failure in test_line_segment_intersection: kmRay2IntersectLineSegment(&ray, &line_start, &line_end, &intersect)
/home/lukeb/Git/kazmath/tests/test_ray2.cpp:65:1: error: Failure in test_triangle_intersection: kmRay2IntersectTriangle(&ray, &p1, &p2, &p3, &intersect, &normal, &dist)
/home/lukeb/Git/kazmath/tests/test_ray2.cpp:66:1: error: Failure in test_triangle_intersection: Expected 0 +/- 0.001 but was -1
/home/lukeb/Git/kazmath/tests/test_ray2.cpp:69:1: error: Failure in test_triangle_intersection: Expected 1 +/- 0.001 but was 4.59163e-41
FAILURE: 3 out of 31 tests failed (8 failures).
```

I believe the top two were failing before, so don't worry about those, but can you see what broke? :)

**Comment by dhontecillas** [comment]
I will check it before this weekend !

**Comment by dhontecillas** [comment]
I've fixed a (stupid) bug in setting a ray by its endpoints. And a test, since the behavior when testing for intersection with a ray, assumes that the ray extends to infinite along the direction it points from its origin.
And there is another function to test if two line segments intersects (i've added it to the tests). In the future i'll try to add more tests since they are proven to be pretty useful. Sorry for the bug.

**Comment by Kazade** [comment]
Merged! Thanks for your great work, and sorry again for taking so long about merging it :)

**Pull request merged**
